# Generated by Django 6.0.4 on 2026-05-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
