# Generated by Django 6.0.4 on 2026-05-08 12:30

from django.db import migrations, models


def set_unknown_director(apps, schema_editor):
    Director = apps.get_model("movies", "Director")
    Movie = apps.get_model("movies", "Movie")
    unknown, _ = Director.objects.get_or_create(
        first_name="Unknown",
        last_name="Director",
    )
    Movie.objects.filter(director__isnull=True).update(director=unknown)


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_movie_genre_name"),
    ]

    operations = [
        migrations.RunPython(set_unknown_director, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="movie",
            name="director",
            field=models.ForeignKey(on_delete=models.CASCADE, to="movies.director"),
        ),
    ]
