# Generated by Django 6.0.4 on 2026-06-04 16:50

from django.db import migrations


def copy_genre_name_to_fk(apps, schema_editor):
    Movie = apps.get_model('movies', 'Movie')
    Genre = apps.get_model('movies', 'Genre')
    for movie in Movie.objects.filter(genre__isnull=True, genre_name__isnull=False).exclude(genre_name=''):
        genre = Genre.objects.filter(name=movie.genre_name).first()
        if genre:
            movie.genre = genre
            movie.save()


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_movie_director_required'),
    ]

    operations = [
        migrations.RunPython(copy_genre_name_to_fk, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='movie',
            name='genre_name',
        ),
    ]
